### PR TITLE
Update SeedCopyCommand.java

### PR DESCRIPTION
**Pull request by xbony2**

### CODE REVIEW

**Comment by elifoster** [comment]
Why?

**Comment by xbony2** [comment]
I looked here to see how to copy something into the clipboard and I was like "what's up with this nonsense".

**Comment by elifoster** [comment]
This code is literally the same.

**Comment by xbony2** [comment]
Except expanded for some reason.

**Comment by elifoster** [comment]
It's harder to read and makes exceptionally less sense.

**Comment by xbony2** [comment]
It's easier to read and makes more sense to me :O

**Pull request closed without merging**
